### ISSUE TITLE
Time values are falling into active text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#153]
```
12:35 PM falls into active-text. Need to fix regex expression.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 29 Apr 2014 at 1:37

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
