### ISSUE TITLE
Double highlight when tapping memorize while already playing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#163]
```
Let something play at ayat 3, then tap memorize from ayat 1 you will see both 3 
and 1 highlighted.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 6 May 2014 at 4:38

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
