### ISSUE TITLE
110:3 is not showing arabic

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#169]
```
10.3 leaked OS 110:3 is not showing arabic
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Jun 2014 at 8:05

Attachments:
- [IMG_20140614_160345.png](https://storage.googleapis.com/google-code-attachments/quran10/issue-169/comment-0/IMG_20140614_160345.png)

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
