### ISSUE TITLE
Support ayat images

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#170]
```
http://www.everyayah.com/data/status.php

Instead of text since there may be rendering problems.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Jun 2014 at 11:44
- Blocking: #184

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
