### ISSUE TITLE
Implement side-by-side comparison of surahs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#223]
```
Long-press on one surah, then select more, and open the second surah to do 
side-by-side comparison
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 15 Jan 2015 at 5:03

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
