### ISSUE TITLE
Introduce additional reciters for specific surahs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#231]
```
This can be from the scholars like Shaykh Al-Albaani, Shaykh Ibn Baaz. The ones 
we don't have everything for, but just some.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 19 Jan 2015 at 5:43

**Comment by canadainc** [comment]
http://www.salaficentre.com/2014/08/recitation-of-the-quran-by-shaikh-ahmad-an-najmi-and-shaikh-zayd/

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=_jHK3pHNuPo

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=5-ZUNWFpJG4

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=0rCwT76cCfs

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=ZiwFVBGHp3o

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=TvYmJOmDM3g

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=JRhSdxRJ9xo

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=Q7Zz60mxhpk

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=Lh5B0mkzn0o

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=dWhPEikMSnI

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=L-L7BmPk7F4

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=G5D8OQUxDs8

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=fMhAyXJQbWs
