### ISSUE TITLE
Implement backup and restore functionality

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#241]
```
Allow bookmarks to be backed up and restored
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 21 Jan 2015 at 5:01

**Comment by canadainc** [comment]
Using Quran10 v4.0.0.5

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
