### ISSUE TITLE
When translations are enabled overlay transliteration on tap of arabic text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#243]
```
Only in ayah page.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 21 Jan 2015 at 7:47

**Comment by canadainc** [comment]
Using Quran10 v4.0.0.5

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
