### ISSUE TITLE
Don't request focus on surah picker text field on non-physical keyboard devices

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#254]
```
Remove on all-touch devices
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 10 Feb 2015 at 7:07

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
