### ISSUE TITLE
Recitations are showing up in the Music app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#277]
```
Downloaded recitations are showing up in the music app and file picker.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 25 Mar 2015 at 9:22

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
