### ISSUE TITLE
Implement automatic tafsir and translation updating

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#279]
```
Allow app to automatically periodically update its tafsir database if newer 
data is available.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 26 Mar 2015 at 9:14

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
