### ISSUE TITLE
Use native surah picker for mushaf sheet

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#280]
```
Don't use the dropdown.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 27 Mar 2015 at 3:14

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
