### ISSUE TITLE
Clean up data folder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#284]
```
From legacy mushaf images.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 7 Apr 2015 at 11:09

**Comment by canadainc** [comment]
12f171a428f9a65096d76532a2ac8d3283f85778

**Comment by canadainc** [comment]
Using Quran10 v4.0.0.5

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
