### ISSUE TITLE
App is sometimes showing new arabic font instead of the classical one

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#285]
```
Due to Cascades bug. Need to work around it.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 9 Apr 2015 at 7:29

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
