### ISSUE TITLE
Don't show the arabic and the translation in the title bar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#289]
```
Only show the translation or show the arabic.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Apr 2015 at 5:08

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
