### ISSUE TITLE
Display the duaa in the supplications pane directly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#290]
```
Instead of linking it
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 13 Apr 2015 at 10:42

**Comment by canadainc** [comment]
Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
