### ISSUE TITLE
Don't show full names for authors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#293]
```
Maximize real estate by not showing full names of authors, but use display 
names wherever we can.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 13 Apr 2015 at 7:52

**Comment by canadainc** [comment]
Pass.
Test using: Quran10 v4.0.0.4

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
