### ISSUE TITLE
Can't seem to pan left to right in the mushaf mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#294]
```
Users are not able to pan left to right in the mushaf mode.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 16 Apr 2015 at 8:54

**Comment by canadainc** [comment]
Opened Mushaf and zoomed and panned left and right.
Test using: Quran10 v4.0.0.4

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
