### ISSUE TITLE
Move all flags to its own settings file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#295]
```
Instead of relying on the main one.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 17 Apr 2015 at 9:47

**Comment by canadainc** [comment]
flags.conf exists, and old settings were removed
Test using: Quran10 v4.0.0.4

Verified on Classic 10.3.2.557
Verified on R081 10.3.1.2744
