### ISSUE TITLE
Move tutorials and flags into their own settings file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#296]
```
Instead of using the main one.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 18 Apr 2015 at 8:21

**Comment by canadainc** [comment]
flags.conf exists
Test using: Quran10 v4.0.0.4

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
