### ISSUE TITLE
No Turkish Translation after the updates

### ISSUE THREAD

**Issue by zead29** [ragaeeb/quran10#422]
Salaam Alaykum. There was turkish translation in the old version. After the update I can not see it anymore. Could you please add it again? Thanks a lot. Regards.

**Comment by canadainc** [comment]
Wa'alaykum salam wa rahmatullahi wabarakathu. This was intentional as the turkish translation was not verified and thus we did not want to keep a translation on our app that may potentially be incorrect.

**Comment by canadainc** [comment]
http://arsiv.diyanetvakfi.org.tr/meal/mealindex.htm

**Comment by canadainc** [comment]
Diyanet Vakfi
