### ISSUE TITLE
Add some missing reciters

### ISSUE THREAD

**Issue by ragaeeb** [ragaeeb/quran10#431]
Some of the ones that have been removed accidentally.

**Comment by canadainc** [comment]
https://shaikhalbaani.wordpress.com/2015/04/09/al-albaani-leading-ishaa-prayer/

**Comment by canadainc** [comment]
https://sughayyirah.wordpress.com/category/quran/recitation-and-reciters/

**Comment by canadainc** [comment]
http://salafitalk.net/st/viewmessages.cfm?Forum=6&Topic=5508

**Comment by canadainc** [comment]
https://twitter.com/salafievent/status/683530079075479552

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=BLRXnTaSiuU

**Comment by canadainc** [comment]
Moosaa Richardson from tumblr

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=OC6AbUGYNdI

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=XUky_UEfz6g

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=_GRVQVU9y3A

**Comment by canadainc** [comment]
https://soundcloud.com/masjidassunnahaston/shaikh-khalid-al-dhafiri-reciting-salah-maghrib-at-masjid-sunnah-an-nabawwiyah-birmingham

**Comment by canadainc** [comment]
https://soundcloud.com/masjidassunnahaston/shaikh-khalid-al-dhafiri-reciting-ishaa-salah-at-masjid-sunnah-an-nabawwiyah-birmingham

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=84IIZW71Dxg

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=YOaROpAfbnA

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=N9RRdGNXRnU&index=5&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=dWhPEikMSnI&index=6&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=vmKJYcvQmZo&index=11&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=i7KN3C8DXs0&index=12&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=wFpFaBdyPZg&index=13&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=rpLMl8bhsqg&index=14&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=HfrTaUz7IHQ&index=15&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=TWr-gVXkG9c&index=16&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=x2fj_5J4n2E&index=17&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=guQzzfKr88U&index=18&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=UZS0N7pMBEY&index=19&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=BfS5QrOyTR0&index=20&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=NBCAii2g_3E&index=21&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=_t8rtL4YVBs&index=22&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=g_s4r4IryGs&index=23&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=u2dmbNidCO0&index=24&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=E1386UfeMo8&index=25&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=9PBUwZKI0kk&index=26&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=0cTbdSzprX0&index=31&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=AU9bySczEEw&index=32&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=IC9TSg8Cg70&index=33&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=YjLig-0oDdg&index=34&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=x2-0pRSBZpQ&index=35&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=TEDPv_Bjg5g&index=36&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=UZxJKyVXtoo&index=37&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=7OAnGZ62-kw&index=38&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=Si_6pXgVf1A&index=39&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=eHbmi-63_6A&index=40&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=1T-sj1y55Nc&index=41&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=C3wCE5v7qWo&index=42&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

https://www.youtube.com/watch?v=sz_fPoeOEhU&index=43&list=PLVJsdIPGwKcuc_VNlc5TGJsjyDD5HtD8v

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=XeNrGFegogI

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=0rCwT76cCfs

https://www.youtube.com/watch?v=Q7Zz60mxhpk

https://www.youtube.com/watch?v=JRhSdxRJ9xo

https://www.youtube.com/watch?v=JddlOv-BUNU

https://www.youtube.com/watch?v=_jHK3pHNuPo

https://www.youtube.com/watch?v=QSkea7zrHj4

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=h91_KM2LyhY

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=ypwvfIdSWbk

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=Lh5B0mkzn0o

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=PE61hMwf_CE

**Comment by canadainc** [comment]
https://www.youtube.com/watch?v=O7LQwCiMOvU
