### ISSUE TITLE
Implement recitation mirrors

### ISSUE THREAD

**Issue by ragaeeb** [ragaeeb/quran10#455]
Everyayah.com is going offline so we will need to host the mp3s on our server.

**Comment by canadainc** [comment]
http://quran.ksu.edu.sa/ayat/?l=en&pg=patches

**Comment by canadainc** [comment]
http://verses.quran.com/Alafasy/mp3/001001.mp3

**Comment by canadainc** [comment]
http://www.quranflash.com/assets/audio/verses/SaltanyDouri/001006.mp3
http://www.quranflash.com/books/Douri/?en&skin=textile&aff#
chrome://net-internals/#events

**Comment by canadainc** [comment]
To allow the user to select from a different source in case original source is down.
