### ISSUE TITLE
Implement juz picker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ragaeeb/quran10#48]
```
Similar to Qu'ran tab, we need to integrate with the Juz.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Aug 2013 at 11:18

**Comment by canadainc** [comment]
413ce097c907bd5d7f71189d3efbe32844913f16

Verified on Passport 10.3.1.2744
Verified on R072 10.3.0.1424
Verified on Classic 10.3.2.557
Verified on Lisbon 10.3.1.2576
Verified on R081 10.3.1.2744
